version: "3.8"

services:
  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    image: govhack-orchestrator
    ports:
      - "3001:3001"
    depends_on:
      - llm

  llm:
    build: ./llm/llm-backend/
    image: govhack-langserve
    ports:
      - "8001:8001"
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY} # pulled from environment variables or .env file
      OPENAI_API_KEY: ${OPENAI_API_KEY} # pulled from environment variables or .env file

